// angular-testanwendung/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = "Angular Testanwendung"
  counter = 0;

  incrementCounter(): void {
    this.counter++;
  }

  resetCounter(): void {
    this.counter = 0;
  }
}
<div>
  <div>
    <h1>Angular Testanwendung</h1>
    <h2>HouseTech</h2>
  </div>
  <div class="content">
    <div class="vertical">
      <button (click)="incrementCounter()">Klick mich!</button>
      <button (click)="resetCounter()">Selbstzerstörung</button>
    </div>
    <div id="card-container">
      <app-display [title]="'Klicks gegeben'" [content]="counter"></app-display>
    </div>
  </div>
</div>

// react-testanwendung/src/App.js
import { useState } from 'react';
import './App.css';
import Card from './Card';

function App() {
  const [counter, setCounter] = useState(0);

  return (
    <div>
      <div>
        <h1>React Testanwendung</h1>
        <h2>HouseTech</h2>
      </div>
      <div className="content">
        <div className="vertical">
          <button onClick={() => setCounter(counter + 1)}>Klick mich!</button>
          <button onClick={() => setCounter(0)}>Selbstzerstörung</button>
        </div>
        <div id="card-container">
          <Card title="Klicks gegeben" content={counter}/>
        </div>
      </div>
    </div>
  );
}

export default App;
